### ISSUE TITLE
Issue with `normalized_weight_setup`

### ISSUE THREAD

**Issue by bonanomi** [uhh-cms/hh2bbww#35]
When running the analysis framework using the latest version of `columnflow` (i.e. checking out `master` in `modules/columnflow`), `cf.ProduceColumns` fails as follows:

  ERROR: luigi-interface - [pid 22242] Worker Worker(salt=6075577198, workers=1, host=[naf-cms17.desy.de](http://naf-cms17.desy.de/), username=markusla, pid=18197) failed    cf.ProduceColumns(effective_workflow=local, branch=0, analysis=hbw.config.analysis_hbw.analysis_hbw, version=v1, config=config_2017_limited, shift=nominal, local_shift=nominal, dataset=st_tchannel_t_powheg, calibrators=skip_jecunc, selector=default, producer=features)
  
  Traceback (most recent call last):
    [...]
    File "/nfs/dust/cms/user/markusla/hh2bbww/modules/columnflow/columnflow/columnar_util.py", line 1916, in run_setup
      self.setup_func(reqs, inputs, reader_targets)
  TypeError: normalized_weight_setup() takes 3 positional arguments but 4 were given

And the issue seems to come from some incompatibility between `normalized_weight_setup` and the current version of `column_flow`.

Checking out `cf` at https://github.com/columnflow/columnflow/commit/851f5d2c2355514a7406bd801f51bc0daab61b32 (maybe also at some of the more recent comments, but we haven't tested it yet).

cc @mafrahm

**Comment by mafrahm** [comment]
This is due to a change from this PR: https://github.com/columnflow/columnflow/pull/242

Should be fixed now.
