### ISSUE TITLE
Category and selector with same requirements give different results

### ISSUE THREAD

**Issue by BalduinLetzer** [uhh-cms/hh2bbww#83]
Using a requirement (like nJet3) in the selector to define the events after cf.ReduceEvents gives a different result, than when using no such requirement or a less stricter one and then building a category for that event (e.g. nJet1 in selector and then nJet3 in category).

[This used nJet3 in the selector](https://github.com/user-attachments/files/16579233/plot__proc_tt_dl__cat_trig_ele_orth__var_electron_pt.pdf)

[This had no jet requirement in the selector but then used a category for nJet3](https://github.com/user-attachments/files/16579247/plot__proc_tt_dl__cat_trig_3j_ele_orth__var_electron_pt.pdf)

This happens when building the category as part of the selection using the selection result, but also when building the selection after ReduceEvents in a producer using the reduced events themselves.

**Comment by mafrahm** [comment]
This issue was a bug in https://github.com/columnflow/columnflow/pull/494 and has been fixed with this commit:

https://github.com/columnflow/columnflow/pull/494/commits/2f3189db8edeea8bea837620398ca00778d6be02
